---
language: go
go:
  - '1.10'
go_import_path: github.com/mvisonneau/gitlab-ci-pipelines-exporter
install:
  - make setup
  - make deps
  - go get -u github.com/mattn/goveralls
script:
  - make all
  - goveralls -service=travis-ci -coverprofile=coverage.out
