version: '3.8'
services:
  redis:
    image: docker.io/bitnami/redis:6.0.9
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  gitlab-ci-pipelines-exporter-1: &gitlab-ci-pipelines-exporter
    image: docker.io/mvisonneau/gitlab-ci-pipelines-exporter:v0.4.6
    # You can comment out the image name and use the following statement
    # to build the image against the current version of the repository
    #build: ../..
    ports:
      - 8081:8080
    links:
      - redis
    environment:
      GCPE_CONFIG: /etc/gitlab-ci-pipelines-exporter/config.yml
      GCPE_LOG_LEVEL: debug
    volumes:
      - ./gitlab-ci-pipelines-exporter/config.yml:/etc/gitlab-ci-pipelines-exporter/config.yml

  gitlab-ci-pipelines-exporter-2:
    <<: *gitlab-ci-pipelines-exporter
    ports:
      - 8082:8080

  gitlab-ci-pipelines-exporter-3:
    <<: *gitlab-ci-pipelines-exporter
    ports:
      - 8083:8080

networks:
  default:
    driver: bridge
