version: '3.8'
services:
  redis:
    image: docker.io/bitnami/redis:6.2
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  gitlab-ci-pipelines-exporter-1: &gitlab-ci-pipelines-exporter
    image: docker.io/mvisonneau/gitlab-ci-pipelines-exporter:v0.4.9
    # You can comment out the image name and use the following statement
    # to build the image against the current version of the repository
    #build: ../..
    ports:
      - 8081:8080
    links:
      - redis
    environment:
      GCPE_CONFIG: /etc/gitlab-ci-pipelines-exporter.yml
    volumes:
      - type: bind
        source: ./gitlab-ci-pipelines-exporter.yml
        target: /etc/gitlab-ci-pipelines-exporter.yml

  gitlab-ci-pipelines-exporter-2:
    <<: *gitlab-ci-pipelines-exporter
    ports:
      - 8082:8080

  gitlab-ci-pipelines-exporter-3:
    <<: *gitlab-ci-pipelines-exporter
    ports:
      - 8083:8080

networks:
  default:
    driver: bridge
