name: 'Close stale issues and PRs'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-slim
    
    permissions:
      actions: write
      contents: write
      issues: write
      pull-requests: write
    
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10
        with:
          exempt-all-pr-assignees: true
          days-before-stale: 180
          days-before-close: 270
          exempt-issue-labels: keep-open
          exempt-pr-labels: keep-open
          delete-branch: true
          operations-per-run: 500
          stale-issue-label: stale
          stale-pr-label: stale
          stale-issue-message: 'This issue has been inactive for ${{ env.days_before_stale}} and is scheduled to close in ${{ env.days_before_close}} days.'
          stale-pr-message: 'This PR has been inactive for ${{ env.days_before_stale}} days and is scheduled to close in ${{ env.days_before_close}} days.'
