version: '3.7'
services:
  gitlab-ci-pipelines-exporter:
    image: mvisonneau/gitlab-ci-pipelines-exporter:0.4.2
    # You can comment out the image name and use the following statement
    # to build the image against the current version of the repository
    #build: ../..
    ports:
      - 8080:8080
    environment:
      GCPE_CONFIG: /etc/gitlab-ci-pipelines-exporter/config.yml
    volumes:
      - type: bind
        source: ./gitlab-ci-pipelines-exporter
        target: /etc/gitlab-ci-pipelines-exporter

  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    links:
      - gitlab-ci-pipelines-exporter
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_INSTALL_PLUGINS: grafana-polystat-panel,yesoreyeram-boomtable-panel
    links:
      - prometheus
    volumes:
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

networks:
  default:
    driver: bridge
